### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by sol3uk** [Samwakelam/06_WEATHER_DASH_SLW#1]
**What did you do well?**
- Stylish UI. 😎 
- Clear theme.
- Optimised for mobile.

**Suggested improvements (Doesn't affect grade)**
- You've still got a few too many unnecessary comments. We wouldn't leave console logs in production code, even commented out 

**GRADE:** A+
[BCS](https://bootcampspot.com/gradebook/79268/grade/63805)

You can let us know about any changes by tagging us in a comment below using "@".

**Comment by Samwakelam** [comment]
@sol3uk  I have updated the suggested amendments, both needs improvement and suggested improvements. Thank you for your help and feedback.

**Comment by sol3uk** [comment]
Very good work @Samwakelam, good to see you've taken onboard the feedback and really ran with it!
